/*import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
*/
import "./globals.css";
import Sidebar from "../components/layout/Sidebar";
import Navbar from "../components/layout/Navbar";

export const metadata = {
  title: "VetCare",
  description: "Sistema de Gestión Veterinaria",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <div className="flex bg-gray-100 min-h-screen">
          <Sidebar />

          <div className="flex-1 flex flex-col">
            <Navbar />

            <main className="p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}